export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
export const SET_USER_PACKAGE_TYPE = 'SET_USER_PACKAGE_TYPE';
export const SET_USER_ROLE = 'SET_USER_ROLE';
export const SET_FEATURES = 'SET_FEATURES';
export const SET_SELECTED_FEATURE = 'SET_SELECTED_FEATURE';
export const SET_OVERVIEW_CONTROLS = 'SET_OVERVIEW_CONTROLS';
export const SET_OVERVIEW_SELECTED_CONTROL = 'SET_OVERVIEW_SELECTED_CONTROL';
export const SET_OVERVIEW_CIRCULAR_PROGRESS_DATA = 'SET_OVERVIEW_CIRCULAR_PROGRESS_DATA';
